In [39]:
import pandas as pd

In [40]:
df=pd.read_csv("top50spotify.csv")

In [41]:
df.head()

,Unnamed: 0,SerialNo.,Track.Name,Artist.Name,Genre,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.,Popularity
0,0,1,Señorita,Shawn Mendes,canadian pop,117,55,76,-6,8,75,191,4,3,79
1,1,2,China,Anuel AA,reggaeton flow,105,81,79,-4,8,61,302,8,9,92
2,2,3,boyfriend (with Social House),Ariana Grande,dance pop,190,80,40,-4,16,70,186,12,46,85
3,3,4,Beautiful People (feat. Khalid),Ed Sheeran,pop,93,65,64,-8,8,55,198,12,19,86
4,4,5,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,150,65,58,-4,11,18,175,45,7,94

### Drop 1st column

In [42]:
df=df.drop(df.columns[0],axis=1)
df.head()

,SerialNo.,Track.Name,Artist.Name,Genre,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.,Popularity
0,1,Señorita,Shawn Mendes,canadian pop,117,55,76,-6,8,75,191,4,3,79
1,2,China,Anuel AA,reggaeton flow,105,81,79,-4,8,61,302,8,9,92
2,3,boyfriend (with Social House),Ariana Grande,dance pop,190,80,40,-4,16,70,186,12,46,85
3,4,Beautiful People (feat. Khalid),Ed Sheeran,pop,93,65,64,-8,8,55,198,12,19,86
4,5,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,150,65,58,-4,11,18,175,45,7,94

### Save this file as top50.csv


df.to_csv("top50.csv", index=False)

### Find the average Energy and Length of first 10 songs.

In [43]:
first_10=df.head(10)

avg_energy=first_10['Energy'].mean()

avg_length=first_10['Length.'].mean()

In [44]:
print('average energy is',avg_energy)
print('average Length is',avg_length)

average energy is 65.1
average Length is 195.6

### Find the total length of songs, group by genre from top to bottom.

In [45]:
df_length= df.groupby('Genre')['Length.'].sum()

# sorting values from top to bottom i.e from highest to lowest
df_length_sort=df['Length.'].sort_values(ascending=False)

print("Sorted list from top to bottom is: \n",df_length_sort)

Sorted list from top to bottom is:
 22    309
1     302
13    288
23    266
15    261
10    251
16    243
40    228
36    226
34    224
29    222
5     220
48    218
42    216
47    214
27    213
26    210
30    210
49    206
14    205
7     202
46    202
33    200
39    199
43    198
3     198
24    195
9     194
28    193
0     191
25    191
2     186
11    185
45    182
12    182
38    181
31    179
32    176
4     175
19    173
41    171
35    164
37    162
44    162
18    161
17    158
8     157
20    153
6     131
21    115
Name: Length., dtype: int64

### Print the artist name with the most number of tracks in one genre. (Hint: Group by artist name and genre)

In [46]:
artist_genre=df.groupby(['Artist.Name','Genre'])['Track.Name'].count().reset_index() # reset_index is used to see output in table format
print(artist_genre.sort_values('Track.Name',ascending=False).head(5))

     Artist.Name         Genre  Track.Name
9     Ed Sheeran           pop           4
19     Lil Nas X   country rap           2
32  Shawn Mendes  canadian pop           2
25    Marshmello       brostep           2
28   Post Malone       dfw rap           2

In [47]:
# above output is coming with index so using to_string to remove index
print(artist_genre.sort_values('Track.Name',ascending=False).head(1).to_string(index=False))

Artist.Name Genre  Track.Name
 Ed Sheeran   pop           4

### Print the data of the tracks created by the artist from the previous question.

In [48]:
artist_data=df.groupby(['Artist.Name','Genre'])['Track.Name'].count().reset_index()
artist_data=artist_data.sort_values('Track.Name',ascending=False)
name=artist_data.iloc[0]['Artist.Name']

print(df[df['Artist.Name']==name])

    SerialNo.                                     Track.Name Artist.Name  \
3           4                Beautiful People (feat. Khalid)  Ed Sheeran
5           6              I Don't Care (with Justin Bieber)  Ed Sheeran
37         38                 Antisocial (with Travis Scott)  Ed Sheeran
49         50  Cross Me (feat. Chance the Rapper & PnB Rock)  Ed Sheeran

   Genre  Beats.Per.Minute  Energy  Danceability  Loudness..dB..  Liveness  \
3    pop                93      65            64              -8         8
5    pop               102      68            80              -5         9
37   pop               152      82            72              -5        36
49   pop                95      79            75              -6         7

    Valence.  Length.  Acousticness..  Speechiness.  Popularity
3         55      198              12            19          86
5         84      220               9             4          84
37        91      162              13             5          87
49        61      206              21            12          82

### Insights
#### - The top artist has maximum track in the dataset
#### -This indicates that he has strong catch in a particular genre.
#### -This also suggest dominance in music sector.